name: CI/CD Pipeline

on:
 push:
   branches: [main]
   paths-ignore:
      - kubernetes/Deployment.yml # to avoild the contenuoes loop we are ignoring this path
 pull_request:
    branches: [main]


jobs:
  scan:
    runs-on: ubuntu-latest
    name: Scan src/ directory only
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up scanner
        run: |
         curl -L https://your-tool-url/install.sh -o install.sh

      - name: Run scan in src/
        run: |
          ./sync-scan --source ./src --output results.sarif
          # Update the command above to match your tool's CLI format
         



    
  
 
