name: CI/CD Pipeline

on:
 push:
   branches: [main]
   paths-ignore:
      - kubernetes/Deployment.yml # to avoild the contenuoes loop we are ignoring this path
 pull_request:
    branches: [main]


jobs:
  codeql:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up CodeQL CLI
      run: |
        gh release download --repo github/codeql-cli-binaries latest --pattern "codeql-linux64.zip"
        unzip codeql-linux64.zip
        sudo mv codeql /opt/codeql
        sudo ln -s /opt/codeql/codeql /usr/local/bin/codeql

    - name: Create CodeQL database (only src/)
      run: |
        codeql database create codeql-db --language=auto --source-root=src

    - name: Run CodeQL analysis on src/
      run: |
        codeql database analyze codeql-db --format=sarifv2.1.0 --output=codeql-report.sarif

    - name: Upload SARIF report
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: codeql-report.sarif
         



    
  
 
